export const Cards = {
  SELECT_CARD: 'SELECT_CARD',
  REQUEST_CARDS_DATA: 'REQUEST_CARDS_DATA',
  RECEIVE_CARDS_DATA: 'RECEIVE_CARDS_DATA',
  FAILED_REQUEST_CARDS_DATA: 'FAILED_REQUEST_CARDS_DATA',
}

export const Receivers = {
  REQUEST_RECEIVERS_DATA: 'REQUEST_RECEIVERS_DATA',
  RECEIVE_RECEIVERS_DATA: 'RECEIVE_RECEIVERS_DATA',
  FAILED_REQUEST_RECEIVERS_DATA: 'FAILED_REQUEST_RECEIVERS_DATA',
}

export const Banks = {
  REQUEST_BANKS_DATA: 'REQUEST_BANKS_DATA',
  RECEIVE_BANKS_DATA: 'RECEIVE_BANKS_DATA',
  FAILED_REQUEST_BANKS_DATA: 'FAILED_REQUEST_BANKS_DATA',
}
