export const Menu = {
  SELECT_TAB: 'SELECT_TAB',
}

export const Cards = {
  SELECT_CARD: 'SELECT_CARD',
  REQUEST_CARDS_DATA: 'REQUEST_CARDS_DATA',
  RECEIVE_CARDS_DATA: 'RECEIVE_CARDS_DATA',
  FAILED_REQUEST_CARDS_DATA: 'FAILED_REQUEST_CARDS_DATA',
}
