export const Cards = {
  SELECT_CARD: 'SELECT_CARD',
  REQUEST_CARDS_DATA: 'REQUEST_CARDS_DATA',
  RECEIVE_CARDS_DATA: 'RECEIVE_CARDS_DATA',
  INVALIDATE_CARDS_DATA: 'INVALIDATE_CARDS_DATA',
  FAILED_REQUEST_CARDS_DATA: 'FAILED_REQUEST_CARDS_DATA',
}

export const Receivers = {
  REQUEST_RECEIVERS_DATA: 'REQUEST_RECEIVERS_DATA',
  RECEIVE_RECEIVERS_DATA: 'RECEIVE_RECEIVERS_DATA',
  INVALIDATE_RECEIVERS_DATA: 'INVALIDATE_RECEIVERS_DATA',
  FAILED_REQUEST_RECEIVERS_DATA: 'FAILED_REQUEST_RECEIVERS_DATA',
}

export const Banks = {
  REQUEST_BANKS_DATA: 'REQUEST_BANKS_DATA',
  RECEIVE_BANKS_DATA: 'RECEIVE_BANKS_DATA',
  FAILED_REQUEST_BANKS_DATA: 'FAILED_REQUEST_BANKS_DATA',
}

export const Debts = {
  REQUEST_DEBTS_DATA_CREATED_BY_YOU: 'REQUEST_DEBTS_DATA_CREATED_BY_YOU',
  RECEIVE_DEBTS_DATA_CREATED_BY_YOU: 'RECEIVE_DEBTS_DATA_CREATED_BY_YOU',
  FAILED_REQUEST_DEBTS_DATA_CREATED_BY_YOU: 'FAILED_REQUEST_DEBTS_DATA_CREATED_BY_YOU',
  INVALIDATE_DEBTS_DATA_CREATED_BY_YOU: 'INVALIDATE_DEBTS_DATA_CREATED_BY_YOU',
  REQUEST_DEBTS_DATA_RECEIVED_FROM_OTHERS: 'REQUEST_DEBTS_DATA_RECEIVED_FROM_OTHERS',
  RECEIVE_DEBTS_DATA_RECEIVED_FROM_OTHERS: 'RECEIVE_DEBTS_DATA_RECEIVED_FROM_OTHERS',
  FAILED_REQUEST_DEBTS_DATA_RECEIVED_FROM_OTHERS: 'FAILED_REQUEST_DEBTS_DATA_RECEIVED_FROM_OTHERS',
  INVALIDATE_DEBTS_DATA_RECEIVED_FROM_OTHERS: 'INVALIDATE_DEBTS_DATA_RECEIVED_FROM_OTHERS',
}
