name: Github Actions Example

on:
  pull_request:
  push:
    paths:
      - "proto/**"
jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: technote-space/get-diff-action@v4
      with:
        PATTERNS: proto/**
        DOT: '...'
        FROM: master
        TO: ${GITHUB_REF##*/}
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      if: env.GIT_DIFF
    - name: Install
      run: npm install
      if: env.GIT_DIFF
