name: Github Actions Example

on:
  pull_request:
  push:
    paths:
      - "proto/**"
jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get branch name (merge)
      if: github.event_name != 'pull_request'
      shell: bash
      run: echo "TO=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
    - name: Get branch name (pull request)
      if: github.event_name == 'pull_request'
      shell: bash
      run: echo "TO=$(echo ${GITHUB_HEAD_REF}" >> $GITHUB_ENV
    - name: Master branch
      run: echo "FROM=master" >> $GITHUB_ENV
    - uses: technote-space/get-diff-action@v4
      with:
        PATTERNS: proto/**
        DOT: '...'
    - name: Branch name
      run: echo running on branch ${{ env.TO }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      if: env.GIT_DIFF
    - name: Install
      run: npm install
      if: env.GIT_DIFF
