name: Github Actions Example

on:
  pull_request:
  push:
    paths:
      - "proto/**"
jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get branch name (merge)
      if: github.event_name != 'pull_request'
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
    - name: Get branch name (pull request)
      if: github.event_name == 'pull_request'
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV
    - uses: technote-space/get-diff-action@v4
      with:
        PATTERNS: proto/**
        DOT: '...'
        FROM: master
        TO: ${{ env.BRANCH_NAME }}
    - name: Branch name
      run: echo running on branch ${{ env.BRANCH_NAME }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      if: env.GIT_DIFF
    - name: Install
      run: npm install
      if: env.GIT_DIFF
